### ISSUE TITLE
请问这是你写的么

### ISSUE THREAD

**Issue by vczyh** [zpj80231/znote#14]
要点脸吧

https://github.com/vuepress-reco/vuepress-theme-reco

**Comment by zpj80231** [comment]
您好，不懂您是什么意思呢？如果您有意见可参考博客置顶文章[ZNOTE GUIDE](https
://zpj80231.gitee.io/znote/tag/)和项目历史提交记录。
有问题请文明交流！谢谢！

**Comment by vczyh** [comment]
> 您好，不懂您是什么意思呢？如果您有意见可参考博客置顶文章（ [ZNOTE GUIDE](https://zpj80231.gitee.io/znote/tag/) ）和项目历史提交记录。
> 
> 有问题请文明交流！谢谢！

https://github.com/vuepress-reco/vuepress-theme-reco

**Comment by zpj80231** [comment]
您好，引用reco主题已在置顶说明呢，znote也在reco官网优blog示例demo页。

另外本项目就是基于早期reco二次修改后的私人博客，本人也同reco作者交流过也为reco有过commit，也写过reco相关文章 [链接](http://zpj80231.gitee.io/znote/views/frontend/reco-info.html)。

最近一直没更新，但是有问题欢迎友好交流哦！

**Comment by vczyh** [comment]
> 您好，引用reco主题就已在GUIDE说明呢，znote也在reco官网示例展示 [theme-example](https://vuepress-theme-reco.recoluan.com/views/other/theme-example.html)。
> 
> 另外本项目就是基于早期reco二次修改后的私人博客，本人也同reco作者交流过也为reco有过commit，也写过reco相关文章 [链接](http://zpj80231.gitee.io/znote/views/frontend/reco-info.html)。
> 
> 最近一直没更新，但是有问题欢迎友好交流哦！
> 
> 从reco建立初期的微信群和Q群我一直都在，有事直接@我就可以，群备注都是znote！

建议你在 README.md 中说明

**Comment by zpj80231** [comment]
OK！

**Comment by zpj80231** [comment]
问题已友好解决！
